# Generated by Django 5.1.4 on 2026-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='geo_affinity',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='geo_category',
            field=models.CharField(choices=[('india', 'India'), ('global', 'Global')], default='india', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
