# Generated by Django 5.1.4 on 2026-04-14 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_hashtag_geo_affinity_news_geo_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('news', 'user')},
        ),
    ]
