# Generated by Django 5.1.4 on 2026-04-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_externalnews_externalcomment_externalshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='emotional_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='factual_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='is_ai_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_tier',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Trusted Contributor', 'Trusted Contributor'), ('Expert Verifier', 'Expert Verifier')], default='Novice', max_length=20),
        ),
        migrations.CreateModel(
            name='TrustVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('verify', 'Verify'), ('dispute', 'Dispute')], max_length=10)),
                ('dispute_reason', models.CharField(choices=[('misleading_title', 'Misleading Title'), ('altered_image', 'Altered Image'), ('outdated_news', 'Outdated News'), ('missing_context', 'Missing Context'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_votes', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'news')},
            },
        ),
    ]
