# Generated by Django 5.1.4 on 2026-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_emotional_score_news_factual_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='emotional_score',
            new_name='ai_emotional_tone',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='factual_score',
            new_name='ai_factual_tone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trust_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trust_tier',
        ),
        migrations.AddField(
            model_name='news',
            name='is_frozen_by_brigading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_echo_chamber_penalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifetime_agreements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifetime_disagreements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='voting_diversity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='TrustVote',
        ),
    ]
